In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder , StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical

In [52]:
df = pd.read_csv('Iris.csv')

In [53]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [54]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [56]:
sns.pairplot(df, hue='Species')

plt.show()

In [57]:
x  = df.drop(columns=['Species','Id'] , axis = 1)
y = df['Species']

In [58]:
encoder = LabelEncoder()
y_int= encoder.fit_transform(y)

In [59]:
y_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [60]:
X_train, X_test, y_train, y_test = train_test_split( x, y_int, test_size=0.2, random_state=42 , stratify=y_int)

In [61]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [62]:
per = Perceptron( max_iter = 1000 , random_state=42)
per.fit(X_train, y_train)

Perceptron(random_state=42)

In [63]:
y_pred_percep = per.predict(X_test)

In [64]:
accuracy_score(y_test, y_pred_percep)

0.8666666666666667

In [65]:
print(classification_report(y_test, y_pred_percep))

              precision    recall  f1-score   support

           0       0.83      1.00      0.91        10
           1       0.88      0.70      0.78        10
           2       0.90      0.90      0.90        10

    accuracy                           0.87        30
   macro avg       0.87      0.87      0.86        30
weighted avg       0.87      0.87      0.86        30

In [66]:
y_train_cat = to_categorical(y_train , num_classes=3)
y_test_cat = to_categorical(y_test ,  num_classes=3)

In [67]:
model = Sequential([
    Dense(16, activation='relu', input_dim=4),
    Dense(8, activation='relu'),
    Dense(3, activation='softmax')
])

In [68]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [69]:
history = model.fit(X_train, y_train_cat, epochs=100, batch_size=8, validation_split=0.2)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - accuracy: 0.6042 - loss: 1.0607 - val_accuracy: 0.6667 - val_loss: 0.9912
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6146 - loss: 0.9830 - val_accuracy: 0.6250 - val_loss: 0.9283
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6042 - loss: 0.9107 - val_accuracy: 0.6667 - val_loss: 0.8544
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6979 - loss: 0.8382 - val_accuracy: 0.7500 - val_loss: 0.7969
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7396 - loss: 0.7811 - val_accuracy: 0.7500 - val_loss: 0.7530
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7500 - loss: 0.7325 - val_accuracy: 0.8333 - val_loss: 0.7174
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7708 - loss: 0.6917 - val_accuracy: 0.8333 - val_loss: 0.6852
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8021 - loss: 0.6559 - val_accuracy: 0.8333 - val_loss: 0.6581
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7917 - loss: 0.6245 - val_accuracy: 0.8333 - val_loss: 0.6335
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8229 - loss: 0.5952 - val_accuracy: 0.8333 - val_loss: 0.6101
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8229 - loss: 0.5689 - val_accuracy: 0.8333 - val_loss: 0.5882
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8438 - loss: 0.5444 - val_accuracy: 0.8333 - val_loss: 0.5668
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8438 - loss: 0.5201 - val_accuracy: 0.8333 - val_loss: 0.5453
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8438 - loss: 0.4977 - val_accuracy: 0.8333 - val_loss: 0.5266
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8438 - loss: 0.4749 - val_accuracy: 0.8333 - val_loss: 0.5064
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8438 - loss: 0.4566 - val_accuracy: 0.8333 - val_loss: 0.4923
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8438 - loss: 0.4355 - val_accuracy: 0.8333 - val_loss: 0.4736
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8438 - loss: 0.4191 - val_accuracy: 0.8333 - val_loss: 0.4589
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8438 - loss: 0.4043 - val_accuracy: 0.8333 - val_loss: 0.4436
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8646 - loss: 0.3907 - val_accuracy: 0.8333 - val_loss: 0.4316
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8750 - loss: 0.3790 - val_accuracy: 0.8333 - val_loss: 0.4197
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8750 - loss: 0.3668 - val_accuracy: 0.8333 - val_loss: 0.4047
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8750 - loss: 0.3553 - val_accuracy: 0.8333 - val_loss: 0.3937
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8854 - loss: 0.3467 - val_accuracy: 0.8333 - val_loss: 0.3847
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8854 - loss: 0.3357 - val_accuracy: 0.8333 - val_loss: 0.3703
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8958 - loss: 0.3263 - val_accuracy: 0.8333 - val_loss: 0.3578
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8958 - loss: 0.3175 - val_accuracy: 0.8333 - val_loss: 0.3403
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.3074 - val_accuracy: 0.8333 - val_loss: 0.3324
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.3000 - val_accuracy: 0.8333 - val_loss: 0.3250
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.2917 - val_accuracy: 0.8750 - val_loss: 0.3111
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9167 - loss: 0.2838 - val_accuracy: 0.9167 - val_loss: 0.2964
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.2746 - val_accuracy: 0.9167 - val_loss: 0.2798
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.2656 - val_accuracy: 0.9167 - val_loss: 0.2715
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.2567 - val_accuracy: 0.9167 - val_loss: 0.2547
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9062 - loss: 0.2493 - val_accuracy: 0.9167 - val_loss: 0.2408
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9062 - loss: 0.2418 - val_accuracy: 0.9583 - val_loss: 0.2331
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.2349 - val_accuracy: 0.9583 - val_loss: 0.2226
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.2289 - val_accuracy: 0.9583 - val_loss: 0.2171
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.2223 - val_accuracy: 0.9583 - val_loss: 0.2069
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9271 - loss: 0.2159 - val_accuracy: 0.9583 - val_loss: 0.1954
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9375 - loss: 0.2103 - val_accuracy: 0.9583 - val_loss: 0.1865
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9375 - loss: 0.2041 - val_accuracy: 0.9583 - val_loss: 0.1797
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9375 - loss: 0.1994 - val_accuracy: 0.9583 - val_loss: 0.1743
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9583 - loss: 0.1940 - val_accuracy: 1.0000 - val_loss: 0.1627
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9583 - loss: 0.1893 - val_accuracy: 1.0000 - val_loss: 0.1568
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9583 - loss: 0.1867 - val_accuracy: 0.9583 - val_loss: 0.1542
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9583 - loss: 0.1803 - val_accuracy: 1.0000 - val_loss: 0.1425
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9583 - loss: 0.1753 - val_accuracy: 1.0000 - val_loss: 0.1370
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9583 - loss: 0.1727 - val_accuracy: 1.0000 - val_loss: 0.1362
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9583 - loss: 0.1672 - val_accuracy: 1.0000 - val_loss: 0.1289
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9583 - loss: 0.1634 - val_accuracy: 1.0000 - val_loss: 0.1234
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9583 - loss: 0.1597 - val_accuracy: 1.0000 - val_loss: 0.1166
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9583 - loss: 0.1573 - val_accuracy: 1.0000 - val_loss: 0.1122
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9583 - loss: 0.1523 - val_accuracy: 1.0000 - val_loss: 0.1099
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9583 - loss: 0.1487 - val_accuracy: 1.0000 - val_loss: 0.1051
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9583 - loss: 0.1449 - val_accuracy: 1.0000 - val_loss: 0.0994
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9583 - loss: 0.1415 - val_accuracy: 1.0000 - val_loss: 0.0962
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9583 - loss: 0.1384 - val_accuracy: 1.0000 - val_loss: 0.0932
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9583 - loss: 0.1348 - val_accuracy: 1.0000 - val_loss: 0.0902
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9583 - loss: 0.1316 - val_accuracy: 1.0000 - val_loss: 0.0870
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9583 - loss: 0.1288 - val_accuracy: 1.0000 - val_loss: 0.0835
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9583 - loss: 0.1278 - val_accuracy: 1.0000 - val_loss: 0.0818
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9583 - loss: 0.1238 - val_accuracy: 1.0000 - val_loss: 0.0774
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9583 - loss: 0.1224 - val_accuracy: 1.0000 - val_loss: 0.0759
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9583 - loss: 0.1196 - val_accuracy: 1.0000 - val_loss: 0.0729
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9583 - loss: 0.1178 - val_accuracy: 1.0000 - val_loss: 0.0700
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9688 - loss: 0.1171 - val_accuracy: 1.0000 - val_loss: 0.0701
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9688 - loss: 0.1134 - val_accuracy: 1.0000 - val_loss: 0.0665
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9583 - loss: 0.1149 - val_accuracy: 1.0000 - val_loss: 0.0629
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9688 - loss: 0.1099 - val_accuracy: 1.0000 - val_loss: 0.0632
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9583 - loss: 0.1084 - val_accuracy: 1.0000 - val_loss: 0.0628
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9688 - loss: 0.1068 - val_accuracy: 1.0000 - val_loss: 0.0595
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9688 - loss: 0.1048 - val_accuracy: 1.0000 - val_loss: 0.0585
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9688 - loss: 0.1033 - val_accuracy: 1.0000 - val_loss: 0.0559
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9688 - loss: 0.1016 - val_accuracy: 1.0000 - val_loss: 0.0549
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9688 - loss: 0.1001 - val_accuracy: 1.0000 - val_loss: 0.0533
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9688 - loss: 0.0994 - val_accuracy: 1.0000 - val_loss: 0.0513
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9688 - loss: 0.0986 - val_accuracy: 1.0000 - val_loss: 0.0512
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9688 - loss: 0.0966 - val_accuracy: 1.0000 - val_loss: 0.0496
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9688 - loss: 0.0954 - val_accuracy: 1.0000 - val_loss: 0.0482
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9688 - loss: 0.0942 - val_accuracy: 1.0000 - val_loss: 0.0466
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9688 - loss: 0.0944 - val_accuracy: 1.0000 - val_loss: 0.0468
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9688 - loss: 0.0915 - val_accuracy: 1.0000 - val_loss: 0.0453
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9688 - loss: 0.0908 - val_accuracy: 1.0000 - val_loss: 0.0439
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9688 - loss: 0.0890 - val_accuracy: 1.0000 - val_loss: 0.0425
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9688 - loss: 0.0898 - val_accuracy: 1.0000 - val_loss: 0.0411
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9688 - loss: 0.0875 - val_accuracy: 1.0000 - val_loss: 0.0406
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9688 - loss: 0.0870 - val_accuracy: 1.0000 - val_loss: 0.0399
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9688 - loss: 0.0854 - val_accuracy: 1.0000 - val_loss: 0.0392
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9688 - loss: 0.0851 - val_accuracy: 1.0000 - val_loss: 0.0385
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9688 - loss: 0.0838 - val_accuracy: 1.0000 - val_loss: 0.0374
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9688 - loss: 0.0843 - val_accuracy: 1.0000 - val_loss: 0.0363
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9688 - loss: 0.0820 - val_accuracy: 1.0000 - val_loss: 0.0363
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9792 - loss: 0.0820 - val_accuracy: 1.0000 - val_loss: 0.0354
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9688 - loss: 0.0816 - val_accuracy: 1.0000 - val_loss: 0.0356
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9792 - loss: 0.0802 - val_accuracy: 1.0000 - val_loss: 0.0342
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9792 - loss: 0.0787 - val_accuracy: 1.0000 - val_loss: 0.0332
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9688 - loss: 0.0792 - val_accuracy: 1.0000 - val_loss: 0.0330
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9792 - loss: 0.0779 - val_accuracy: 1.0000 - val_loss: 0.0320
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9688 - loss: 0.0787 - val_accuracy: 1.0000 - val_loss: 0.0313

In [70]:
loss, accuracy = model.evaluate(X_test, y_test_cat , verbose=1)
print('Test Loss:', loss)
print('Test Accuracy:', accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step - accuracy: 0.9333 - loss: 0.1346
Test Loss: 0.1346430778503418
Test Accuracy: 0.9333333373069763

In [71]:
plt.figure(figsize=(12, 4))
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')